---
-
- hosts: all
  tasks:
    - name : Copy Docker file to QA Server
      copy:
       src: Dockerfile
       dest: .
    - name: Copy Index File to QA Server
      copy:
       src: index.html
       dest: .
    - name: Create Docker image
      command: sudo docker build -t image1 .
      ignore_errors: True
    - name: Create Container from image
      command: sudo docker run -d -p 8080:8080 --name cont1 image1
      ignore_errors: True


