---
- hosts: all
  tasks:
    - name: Copy files from App-Server to QA Server
      copy:
        dest: .
        src: '{{item}}'
      loop:
        - index.html
        - Dockerfile

    - name: Stop the running container
      become: yes
      command: docker stop cont2
      ignore_errors: True

    - name: Removing the container1
      become: yes      
      command: docker rm cont2
      ignore_errors: True

    - name: Removing the docker image
      become: yes
      command: docker rmi -f image2
      ignore_errors: True

    - name: Create Docker image
      become: yes
      command: docker build -t image2 .

    - name: Create container from Image
      become: yes
      command: docker run -d -p 8080:8080 --name cont2 image2
      
